// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpqgrondgpgaohbtdbji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwcWdyb25kZ3BnYW9oYnRkYmppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxODQ0NjksImV4cCI6MjA1Nzc2MDQ2OX0.DmPwGEeo2Zyb37EMTOTne8e7Gx72eKbj7EPbHgqTB_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);